### ISSUE TITLE
How do you handle dynamic IPs with NAT?

### ISSUE THREAD

**Issue by Jiehong** [scoulomb/myDNS#1]
Hi,

In 6-use-linux-nameserver.md, do you have a static IP provided by your Internet provider?

In my case, I have a dynamic one, so I wanted to know if you have an idea how to deal with this instead.

**Comment by scoulomb** [comment]
@Jiehong Very good point. My IP is also not static. We can use a dynamic DNS to solve this.
It will provide a FQDN and update the IP dynamically.

We can choose noip
https://my.noip.com/#!/dynamic-dns

And create a dns name like `scoulomb.ddns.net`

In my box (SFR)
We would go there : http://192.168.1.1/network/ddns ( Home > Réseau v4 > DynDNS)
And was able to map noip service (nothing to install on my machine).

Then I could do:

````
nslookup scoulomb.ddns.net 8.8.8.8
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    scoulomb.ddns.net
Address:  <my-box-ip>
``````

We could then define a CNAME (in your nameserver) such as `myhome.coulombel.it` to `scoulomb.ddns.net`.
